# Generated by Django 4.2.4 on 2024-01-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTTsubcription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ott',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='review', to='OTTsubcription.review'),
        ),
    ]
