# Generated by Django 4.2.4 on 2024-01-17 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OTTsubcription', '0002_alter_ott_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ott',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.CreateModel(
            name='OTTSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.BooleanField(default=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months')])),
                ('cost', models.IntegerField()),
                ('shared', models.BooleanField(default=False)),
                ('ott', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ott', to='OTTsubcription.ott')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_with', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
