# Generated by Django 4.2.4 on 2024-01-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTTsubcription', '0004_alter_ottsubscription_subscribed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ottsubscription',
            name='subscribed_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
