# Generated by Django 4.2.4 on 2024-01-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTTsubcription', '0005_ottsubscription_subscribed_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ottsubscription',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months')]),
        ),
        migrations.AlterField(
            model_name='ottsubscription',
            name='subscribed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ottsubscription',
            name='subscribed_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
