# Generated by Django 4.2.4 on 2024-01-17 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OTTsubcription', '0006_alter_ottsubscription_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ott',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='ott',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_ott', to='OTTsubcription.ott'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
