# Generated by Django 4.2.4 on 2024-01-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='created',
        ),
    ]
