# Generated by Django 5.0.1 on 2024-01-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
